SESSION_OUTCOMES = {
    "FAIL": "Fail",
    "SUCCESS_BOTH": "Success_both",
    "SUCCESS_ROBOT": "Success_robot",
    "SUCCESS_SIM": "Success_sim",
    "ABANDONED": "Abandoned",
}

SESSION_OUTCOME_PRIORITY = (
    SESSION_OUTCOMES["SUCCESS_BOTH"],
    SESSION_OUTCOMES["SUCCESS_ROBOT"],
    SESSION_OUTCOMES["SUCCESS_SIM"],
    SESSION_OUTCOMES["ABANDONED"],
    SESSION_OUTCOMES["FAIL"],
)