/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SolveIndexRouteImport } from './routes/solve/index'
import { Route as AdminRobotsRouteImport } from './routes/admin/robots'
import { Route as SolveActivityTaskIdIndexRouteImport } from './routes/solve/$activityTaskId/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminTasksIndexRouteImport } from './routes/admin/tasks/index'
import { Route as AdminBadgesIndexRouteImport } from './routes/admin/badges/index'
import { Route as AdminAnalyticsIndexRouteImport } from './routes/admin/analytics/index'
import { Route as AdminActivitiesIndexRouteImport } from './routes/admin/activities/index'
import { Route as AdminUsersNewRouteImport } from './routes/admin/users/new'
import { Route as AdminTasksNewRouteImport } from './routes/admin/tasks/new'
import { Route as AdminBadgesNewRouteImport } from './routes/admin/badges/new'
import { Route as AdminActivitiesNewRouteImport } from './routes/admin/activities/new'
import { Route as AdminTasksTaskIdRouteRouteImport } from './routes/admin/tasks/$taskId/route'
import { Route as AdminUsersGroupsIndexRouteImport } from './routes/admin/users/groups/index'
import { Route as AdminUsersUserIdIndexRouteImport } from './routes/admin/users/$userId/index'
import { Route as AdminTasksTaskIdIndexRouteImport } from './routes/admin/tasks/$taskId/index'
import { Route as AdminActivitiesActivityIdIndexRouteImport } from './routes/admin/activities/$activityId/index'
import { Route as AdminUsersGroupsNewRouteImport } from './routes/admin/users/groups/new'
import { Route as AdminUsersUserIdEditRouteImport } from './routes/admin/users/$userId/edit'
import { Route as AdminTasksTaskIdEditRouteImport } from './routes/admin/tasks/$taskId/edit'
import { Route as AdminBadgesBadgeIdEditRouteImport } from './routes/admin/badges/$badgeId/edit'
import { Route as AdminActivitiesActivityIdEditRouteImport } from './routes/admin/activities/$activityId/edit'
import { Route as AdminUsersGroupsGroupIdIndexRouteImport } from './routes/admin/users/groups/$groupId/index'
import { Route as AdminAnalyticsStudentStudentIdIndexRouteImport } from './routes/admin/analytics/student/$studentId/index'
import { Route as AdminUsersGroupsGroupIdMembersRouteImport } from './routes/admin/users/groups/$groupId/members'
import { Route as AdminActivitiesActivityIdTasksAddRouteImport } from './routes/admin/activities/$activityId/tasks/add'
import { Route as AdminActivitiesActivityIdTasksActivityTaskIdStudentsRouteImport } from './routes/admin/activities/$activityId/tasks/$activityTaskId/students'
import { Route as AdminActivitiesActivityIdTasksActivityTaskIdEditRouteImport } from './routes/admin/activities/$activityId/tasks/$activityTaskId/edit'

const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SolveIndexRoute = SolveIndexRouteImport.update({
  id: '/solve/',
  path: '/solve/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRobotsRoute = AdminRobotsRouteImport.update({
  id: '/robots',
  path: '/robots',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SolveActivityTaskIdIndexRoute =
  SolveActivityTaskIdIndexRouteImport.update({
    id: '/solve/$activityTaskId/',
    path: '/solve/$activityTaskId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksIndexRoute = AdminTasksIndexRouteImport.update({
  id: '/tasks/',
  path: '/tasks/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBadgesIndexRoute = AdminBadgesIndexRouteImport.update({
  id: '/badges/',
  path: '/badges/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsIndexRoute = AdminAnalyticsIndexRouteImport.update({
  id: '/analytics/',
  path: '/analytics/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivitiesIndexRoute = AdminActivitiesIndexRouteImport.update({
  id: '/activities/',
  path: '/activities/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersNewRoute = AdminUsersNewRouteImport.update({
  id: '/users/new',
  path: '/users/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksNewRoute = AdminTasksNewRouteImport.update({
  id: '/tasks/new',
  path: '/tasks/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBadgesNewRoute = AdminBadgesNewRouteImport.update({
  id: '/badges/new',
  path: '/badges/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivitiesNewRoute = AdminActivitiesNewRouteImport.update({
  id: '/activities/new',
  path: '/activities/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksTaskIdRouteRoute = AdminTasksTaskIdRouteRouteImport.update({
  id: '/tasks/$taskId',
  path: '/tasks/$taskId',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersGroupsIndexRoute = AdminUsersGroupsIndexRouteImport.update({
  id: '/users/groups/',
  path: '/users/groups/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdIndexRoute = AdminUsersUserIdIndexRouteImport.update({
  id: '/users/$userId/',
  path: '/users/$userId/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksTaskIdIndexRoute = AdminTasksTaskIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminTasksTaskIdRouteRoute,
} as any)
const AdminActivitiesActivityIdIndexRoute =
  AdminActivitiesActivityIdIndexRouteImport.update({
    id: '/activities/$activityId/',
    path: '/activities/$activityId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersGroupsNewRoute = AdminUsersGroupsNewRouteImport.update({
  id: '/users/groups/new',
  path: '/users/groups/new',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminUsersUserIdEditRoute = AdminUsersUserIdEditRouteImport.update({
  id: '/users/$userId/edit',
  path: '/users/$userId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminTasksTaskIdEditRoute = AdminTasksTaskIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AdminTasksTaskIdRouteRoute,
} as any)
const AdminBadgesBadgeIdEditRoute = AdminBadgesBadgeIdEditRouteImport.update({
  id: '/badges/$badgeId/edit',
  path: '/badges/$badgeId/edit',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminActivitiesActivityIdEditRoute =
  AdminActivitiesActivityIdEditRouteImport.update({
    id: '/activities/$activityId/edit',
    path: '/activities/$activityId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersGroupsGroupIdIndexRoute =
  AdminUsersGroupsGroupIdIndexRouteImport.update({
    id: '/users/groups/$groupId/',
    path: '/users/groups/$groupId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminAnalyticsStudentStudentIdIndexRoute =
  AdminAnalyticsStudentStudentIdIndexRouteImport.update({
    id: '/analytics/student/$studentId/',
    path: '/analytics/student/$studentId/',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminUsersGroupsGroupIdMembersRoute =
  AdminUsersGroupsGroupIdMembersRouteImport.update({
    id: '/users/groups/$groupId/members',
    path: '/users/groups/$groupId/members',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminActivitiesActivityIdTasksAddRoute =
  AdminActivitiesActivityIdTasksAddRouteImport.update({
    id: '/activities/$activityId/tasks/add',
    path: '/activities/$activityId/tasks/add',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute =
  AdminActivitiesActivityIdTasksActivityTaskIdStudentsRouteImport.update({
    id: '/activities/$activityId/tasks/$activityTaskId/students',
    path: '/activities/$activityId/tasks/$activityTaskId/students',
    getParentRoute: () => AdminRouteRoute,
  } as any)
const AdminActivitiesActivityIdTasksActivityTaskIdEditRoute =
  AdminActivitiesActivityIdTasksActivityTaskIdEditRouteImport.update({
    id: '/activities/$activityId/tasks/$activityTaskId/edit',
    path: '/activities/$activityId/tasks/$activityTaskId/edit',
    getParentRoute: () => AdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/solve/': typeof SolveIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRouteRouteWithChildren
  '/admin/activities/new': typeof AdminActivitiesNewRoute
  '/admin/badges/new': typeof AdminBadgesNewRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/activities/': typeof AdminActivitiesIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/badges/': typeof AdminBadgesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/solve/$activityTaskId/': typeof SolveActivityTaskIdIndexRoute
  '/admin/activities/$activityId/edit': typeof AdminActivitiesActivityIdEditRoute
  '/admin/badges/$badgeId/edit': typeof AdminBadgesBadgeIdEditRoute
  '/admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/users/groups/new': typeof AdminUsersGroupsNewRoute
  '/admin/activities/$activityId/': typeof AdminActivitiesActivityIdIndexRoute
  '/admin/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/users/groups/': typeof AdminUsersGroupsIndexRoute
  '/admin/activities/$activityId/tasks/add': typeof AdminActivitiesActivityIdTasksAddRoute
  '/admin/users/groups/$groupId/members': typeof AdminUsersGroupsGroupIdMembersRoute
  '/admin/analytics/student/$studentId/': typeof AdminAnalyticsStudentStudentIdIndexRoute
  '/admin/users/groups/$groupId/': typeof AdminUsersGroupsGroupIdIndexRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/edit': typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/students': typeof AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/solve': typeof SolveIndexRoute
  '/admin/activities/new': typeof AdminActivitiesNewRoute
  '/admin/badges/new': typeof AdminBadgesNewRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/activities': typeof AdminActivitiesIndexRoute
  '/admin/analytics': typeof AdminAnalyticsIndexRoute
  '/admin/badges': typeof AdminBadgesIndexRoute
  '/admin/tasks': typeof AdminTasksIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/solve/$activityTaskId': typeof SolveActivityTaskIdIndexRoute
  '/admin/activities/$activityId/edit': typeof AdminActivitiesActivityIdEditRoute
  '/admin/badges/$badgeId/edit': typeof AdminBadgesBadgeIdEditRoute
  '/admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/users/groups/new': typeof AdminUsersGroupsNewRoute
  '/admin/activities/$activityId': typeof AdminActivitiesActivityIdIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdIndexRoute
  '/admin/users/$userId': typeof AdminUsersUserIdIndexRoute
  '/admin/users/groups': typeof AdminUsersGroupsIndexRoute
  '/admin/activities/$activityId/tasks/add': typeof AdminActivitiesActivityIdTasksAddRoute
  '/admin/users/groups/$groupId/members': typeof AdminUsersGroupsGroupIdMembersRoute
  '/admin/analytics/student/$studentId': typeof AdminAnalyticsStudentStudentIdIndexRoute
  '/admin/users/groups/$groupId': typeof AdminUsersGroupsGroupIdIndexRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/edit': typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/students': typeof AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/admin/robots': typeof AdminRobotsRoute
  '/solve/': typeof SolveIndexRoute
  '/admin/tasks/$taskId': typeof AdminTasksTaskIdRouteRouteWithChildren
  '/admin/activities/new': typeof AdminActivitiesNewRoute
  '/admin/badges/new': typeof AdminBadgesNewRoute
  '/admin/tasks/new': typeof AdminTasksNewRoute
  '/admin/users/new': typeof AdminUsersNewRoute
  '/admin/activities/': typeof AdminActivitiesIndexRoute
  '/admin/analytics/': typeof AdminAnalyticsIndexRoute
  '/admin/badges/': typeof AdminBadgesIndexRoute
  '/admin/tasks/': typeof AdminTasksIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/solve/$activityTaskId/': typeof SolveActivityTaskIdIndexRoute
  '/admin/activities/$activityId/edit': typeof AdminActivitiesActivityIdEditRoute
  '/admin/badges/$badgeId/edit': typeof AdminBadgesBadgeIdEditRoute
  '/admin/tasks/$taskId/edit': typeof AdminTasksTaskIdEditRoute
  '/admin/users/$userId/edit': typeof AdminUsersUserIdEditRoute
  '/admin/users/groups/new': typeof AdminUsersGroupsNewRoute
  '/admin/activities/$activityId/': typeof AdminActivitiesActivityIdIndexRoute
  '/admin/tasks/$taskId/': typeof AdminTasksTaskIdIndexRoute
  '/admin/users/$userId/': typeof AdminUsersUserIdIndexRoute
  '/admin/users/groups/': typeof AdminUsersGroupsIndexRoute
  '/admin/activities/$activityId/tasks/add': typeof AdminActivitiesActivityIdTasksAddRoute
  '/admin/users/groups/$groupId/members': typeof AdminUsersGroupsGroupIdMembersRoute
  '/admin/analytics/student/$studentId/': typeof AdminAnalyticsStudentStudentIdIndexRoute
  '/admin/users/groups/$groupId/': typeof AdminUsersGroupsGroupIdIndexRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/edit': typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
  '/admin/activities/$activityId/tasks/$activityTaskId/students': typeof AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/profile'
    | '/admin/robots'
    | '/solve/'
    | '/admin/tasks/$taskId'
    | '/admin/activities/new'
    | '/admin/badges/new'
    | '/admin/tasks/new'
    | '/admin/users/new'
    | '/admin/activities/'
    | '/admin/analytics/'
    | '/admin/badges/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/solve/$activityTaskId/'
    | '/admin/activities/$activityId/edit'
    | '/admin/badges/$badgeId/edit'
    | '/admin/tasks/$taskId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/users/groups/new'
    | '/admin/activities/$activityId/'
    | '/admin/tasks/$taskId/'
    | '/admin/users/$userId/'
    | '/admin/users/groups/'
    | '/admin/activities/$activityId/tasks/add'
    | '/admin/users/groups/$groupId/members'
    | '/admin/analytics/student/$studentId/'
    | '/admin/users/groups/$groupId/'
    | '/admin/activities/$activityId/tasks/$activityTaskId/edit'
    | '/admin/activities/$activityId/tasks/$activityTaskId/students'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/profile'
    | '/admin/robots'
    | '/solve'
    | '/admin/activities/new'
    | '/admin/badges/new'
    | '/admin/tasks/new'
    | '/admin/users/new'
    | '/admin/activities'
    | '/admin/analytics'
    | '/admin/badges'
    | '/admin/tasks'
    | '/admin/users'
    | '/solve/$activityTaskId'
    | '/admin/activities/$activityId/edit'
    | '/admin/badges/$badgeId/edit'
    | '/admin/tasks/$taskId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/users/groups/new'
    | '/admin/activities/$activityId'
    | '/admin/tasks/$taskId'
    | '/admin/users/$userId'
    | '/admin/users/groups'
    | '/admin/activities/$activityId/tasks/add'
    | '/admin/users/groups/$groupId/members'
    | '/admin/analytics/student/$studentId'
    | '/admin/users/groups/$groupId'
    | '/admin/activities/$activityId/tasks/$activityTaskId/edit'
    | '/admin/activities/$activityId/tasks/$activityTaskId/students'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/about'
    | '/login'
    | '/profile'
    | '/admin/robots'
    | '/solve/'
    | '/admin/tasks/$taskId'
    | '/admin/activities/new'
    | '/admin/badges/new'
    | '/admin/tasks/new'
    | '/admin/users/new'
    | '/admin/activities/'
    | '/admin/analytics/'
    | '/admin/badges/'
    | '/admin/tasks/'
    | '/admin/users/'
    | '/solve/$activityTaskId/'
    | '/admin/activities/$activityId/edit'
    | '/admin/badges/$badgeId/edit'
    | '/admin/tasks/$taskId/edit'
    | '/admin/users/$userId/edit'
    | '/admin/users/groups/new'
    | '/admin/activities/$activityId/'
    | '/admin/tasks/$taskId/'
    | '/admin/users/$userId/'
    | '/admin/users/groups/'
    | '/admin/activities/$activityId/tasks/add'
    | '/admin/users/groups/$groupId/members'
    | '/admin/analytics/student/$studentId/'
    | '/admin/users/groups/$groupId/'
    | '/admin/activities/$activityId/tasks/$activityTaskId/edit'
    | '/admin/activities/$activityId/tasks/$activityTaskId/students'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  SolveIndexRoute: typeof SolveIndexRoute
  SolveActivityTaskIdIndexRoute: typeof SolveActivityTaskIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solve/': {
      id: '/solve/'
      path: '/solve'
      fullPath: '/solve/'
      preLoaderRoute: typeof SolveIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/robots': {
      id: '/admin/robots'
      path: '/robots'
      fullPath: '/admin/robots'
      preLoaderRoute: typeof AdminRobotsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/solve/$activityTaskId/': {
      id: '/solve/$activityTaskId/'
      path: '/solve/$activityTaskId'
      fullPath: '/solve/$activityTaskId/'
      preLoaderRoute: typeof SolveActivityTaskIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/': {
      id: '/admin/tasks/'
      path: '/tasks'
      fullPath: '/admin/tasks/'
      preLoaderRoute: typeof AdminTasksIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/badges/': {
      id: '/admin/badges/'
      path: '/badges'
      fullPath: '/admin/badges/'
      preLoaderRoute: typeof AdminBadgesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/': {
      id: '/admin/analytics/'
      path: '/analytics'
      fullPath: '/admin/analytics/'
      preLoaderRoute: typeof AdminAnalyticsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/': {
      id: '/admin/activities/'
      path: '/activities'
      fullPath: '/admin/activities/'
      preLoaderRoute: typeof AdminActivitiesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/new': {
      id: '/admin/users/new'
      path: '/users/new'
      fullPath: '/admin/users/new'
      preLoaderRoute: typeof AdminUsersNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/new': {
      id: '/admin/tasks/new'
      path: '/tasks/new'
      fullPath: '/admin/tasks/new'
      preLoaderRoute: typeof AdminTasksNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/badges/new': {
      id: '/admin/badges/new'
      path: '/badges/new'
      fullPath: '/admin/badges/new'
      preLoaderRoute: typeof AdminBadgesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/new': {
      id: '/admin/activities/new'
      path: '/activities/new'
      fullPath: '/admin/activities/new'
      preLoaderRoute: typeof AdminActivitiesNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/$taskId': {
      id: '/admin/tasks/$taskId'
      path: '/tasks/$taskId'
      fullPath: '/admin/tasks/$taskId'
      preLoaderRoute: typeof AdminTasksTaskIdRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/groups/': {
      id: '/admin/users/groups/'
      path: '/users/groups'
      fullPath: '/admin/users/groups/'
      preLoaderRoute: typeof AdminUsersGroupsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/': {
      id: '/admin/users/$userId/'
      path: '/users/$userId'
      fullPath: '/admin/users/$userId/'
      preLoaderRoute: typeof AdminUsersUserIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/$taskId/': {
      id: '/admin/tasks/$taskId/'
      path: '/'
      fullPath: '/admin/tasks/$taskId/'
      preLoaderRoute: typeof AdminTasksTaskIdIndexRouteImport
      parentRoute: typeof AdminTasksTaskIdRouteRoute
    }
    '/admin/activities/$activityId/': {
      id: '/admin/activities/$activityId/'
      path: '/activities/$activityId'
      fullPath: '/admin/activities/$activityId/'
      preLoaderRoute: typeof AdminActivitiesActivityIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/groups/new': {
      id: '/admin/users/groups/new'
      path: '/users/groups/new'
      fullPath: '/admin/users/groups/new'
      preLoaderRoute: typeof AdminUsersGroupsNewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/$userId/edit': {
      id: '/admin/users/$userId/edit'
      path: '/users/$userId/edit'
      fullPath: '/admin/users/$userId/edit'
      preLoaderRoute: typeof AdminUsersUserIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/tasks/$taskId/edit': {
      id: '/admin/tasks/$taskId/edit'
      path: '/edit'
      fullPath: '/admin/tasks/$taskId/edit'
      preLoaderRoute: typeof AdminTasksTaskIdEditRouteImport
      parentRoute: typeof AdminTasksTaskIdRouteRoute
    }
    '/admin/badges/$badgeId/edit': {
      id: '/admin/badges/$badgeId/edit'
      path: '/badges/$badgeId/edit'
      fullPath: '/admin/badges/$badgeId/edit'
      preLoaderRoute: typeof AdminBadgesBadgeIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/$activityId/edit': {
      id: '/admin/activities/$activityId/edit'
      path: '/activities/$activityId/edit'
      fullPath: '/admin/activities/$activityId/edit'
      preLoaderRoute: typeof AdminActivitiesActivityIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/groups/$groupId/': {
      id: '/admin/users/groups/$groupId/'
      path: '/users/groups/$groupId'
      fullPath: '/admin/users/groups/$groupId/'
      preLoaderRoute: typeof AdminUsersGroupsGroupIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics/student/$studentId/': {
      id: '/admin/analytics/student/$studentId/'
      path: '/analytics/student/$studentId'
      fullPath: '/admin/analytics/student/$studentId/'
      preLoaderRoute: typeof AdminAnalyticsStudentStudentIdIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/users/groups/$groupId/members': {
      id: '/admin/users/groups/$groupId/members'
      path: '/users/groups/$groupId/members'
      fullPath: '/admin/users/groups/$groupId/members'
      preLoaderRoute: typeof AdminUsersGroupsGroupIdMembersRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/$activityId/tasks/add': {
      id: '/admin/activities/$activityId/tasks/add'
      path: '/activities/$activityId/tasks/add'
      fullPath: '/admin/activities/$activityId/tasks/add'
      preLoaderRoute: typeof AdminActivitiesActivityIdTasksAddRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/$activityId/tasks/$activityTaskId/students': {
      id: '/admin/activities/$activityId/tasks/$activityTaskId/students'
      path: '/activities/$activityId/tasks/$activityTaskId/students'
      fullPath: '/admin/activities/$activityId/tasks/$activityTaskId/students'
      preLoaderRoute: typeof AdminActivitiesActivityIdTasksActivityTaskIdStudentsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/activities/$activityId/tasks/$activityTaskId/edit': {
      id: '/admin/activities/$activityId/tasks/$activityTaskId/edit'
      path: '/activities/$activityId/tasks/$activityTaskId/edit'
      fullPath: '/admin/activities/$activityId/tasks/$activityTaskId/edit'
      preLoaderRoute: typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRouteImport
      parentRoute: typeof AdminRouteRoute
    }
  }
}

interface AdminTasksTaskIdRouteRouteChildren {
  AdminTasksTaskIdEditRoute: typeof AdminTasksTaskIdEditRoute
  AdminTasksTaskIdIndexRoute: typeof AdminTasksTaskIdIndexRoute
}

const AdminTasksTaskIdRouteRouteChildren: AdminTasksTaskIdRouteRouteChildren = {
  AdminTasksTaskIdEditRoute: AdminTasksTaskIdEditRoute,
  AdminTasksTaskIdIndexRoute: AdminTasksTaskIdIndexRoute,
}

const AdminTasksTaskIdRouteRouteWithChildren =
  AdminTasksTaskIdRouteRoute._addFileChildren(
    AdminTasksTaskIdRouteRouteChildren,
  )

interface AdminRouteRouteChildren {
  AdminRobotsRoute: typeof AdminRobotsRoute
  AdminTasksTaskIdRouteRoute: typeof AdminTasksTaskIdRouteRouteWithChildren
  AdminActivitiesNewRoute: typeof AdminActivitiesNewRoute
  AdminBadgesNewRoute: typeof AdminBadgesNewRoute
  AdminTasksNewRoute: typeof AdminTasksNewRoute
  AdminUsersNewRoute: typeof AdminUsersNewRoute
  AdminActivitiesIndexRoute: typeof AdminActivitiesIndexRoute
  AdminAnalyticsIndexRoute: typeof AdminAnalyticsIndexRoute
  AdminBadgesIndexRoute: typeof AdminBadgesIndexRoute
  AdminTasksIndexRoute: typeof AdminTasksIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
  AdminActivitiesActivityIdEditRoute: typeof AdminActivitiesActivityIdEditRoute
  AdminBadgesBadgeIdEditRoute: typeof AdminBadgesBadgeIdEditRoute
  AdminUsersUserIdEditRoute: typeof AdminUsersUserIdEditRoute
  AdminUsersGroupsNewRoute: typeof AdminUsersGroupsNewRoute
  AdminActivitiesActivityIdIndexRoute: typeof AdminActivitiesActivityIdIndexRoute
  AdminUsersUserIdIndexRoute: typeof AdminUsersUserIdIndexRoute
  AdminUsersGroupsIndexRoute: typeof AdminUsersGroupsIndexRoute
  AdminActivitiesActivityIdTasksAddRoute: typeof AdminActivitiesActivityIdTasksAddRoute
  AdminUsersGroupsGroupIdMembersRoute: typeof AdminUsersGroupsGroupIdMembersRoute
  AdminAnalyticsStudentStudentIdIndexRoute: typeof AdminAnalyticsStudentStudentIdIndexRoute
  AdminUsersGroupsGroupIdIndexRoute: typeof AdminUsersGroupsGroupIdIndexRoute
  AdminActivitiesActivityIdTasksActivityTaskIdEditRoute: typeof AdminActivitiesActivityIdTasksActivityTaskIdEditRoute
  AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute: typeof AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminRobotsRoute: AdminRobotsRoute,
  AdminTasksTaskIdRouteRoute: AdminTasksTaskIdRouteRouteWithChildren,
  AdminActivitiesNewRoute: AdminActivitiesNewRoute,
  AdminBadgesNewRoute: AdminBadgesNewRoute,
  AdminTasksNewRoute: AdminTasksNewRoute,
  AdminUsersNewRoute: AdminUsersNewRoute,
  AdminActivitiesIndexRoute: AdminActivitiesIndexRoute,
  AdminAnalyticsIndexRoute: AdminAnalyticsIndexRoute,
  AdminBadgesIndexRoute: AdminBadgesIndexRoute,
  AdminTasksIndexRoute: AdminTasksIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
  AdminActivitiesActivityIdEditRoute: AdminActivitiesActivityIdEditRoute,
  AdminBadgesBadgeIdEditRoute: AdminBadgesBadgeIdEditRoute,
  AdminUsersUserIdEditRoute: AdminUsersUserIdEditRoute,
  AdminUsersGroupsNewRoute: AdminUsersGroupsNewRoute,
  AdminActivitiesActivityIdIndexRoute: AdminActivitiesActivityIdIndexRoute,
  AdminUsersUserIdIndexRoute: AdminUsersUserIdIndexRoute,
  AdminUsersGroupsIndexRoute: AdminUsersGroupsIndexRoute,
  AdminActivitiesActivityIdTasksAddRoute:
    AdminActivitiesActivityIdTasksAddRoute,
  AdminUsersGroupsGroupIdMembersRoute: AdminUsersGroupsGroupIdMembersRoute,
  AdminAnalyticsStudentStudentIdIndexRoute:
    AdminAnalyticsStudentStudentIdIndexRoute,
  AdminUsersGroupsGroupIdIndexRoute: AdminUsersGroupsGroupIdIndexRoute,
  AdminActivitiesActivityIdTasksActivityTaskIdEditRoute:
    AdminActivitiesActivityIdTasksActivityTaskIdEditRoute,
  AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute:
    AdminActivitiesActivityIdTasksActivityTaskIdStudentsRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  SolveIndexRoute: SolveIndexRoute,
  SolveActivityTaskIdIndexRoute: SolveActivityTaskIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
