"""add-programming-elements

Revision ID: 1da3ca7ba2cd
Revises: a2fa3e9ae30b
Create Date: 2026-10-05 12:14:40.934751

"""
from alembic import op
import sqlalchemy as sa
import datetime


# revision identifiers, used by Alembic.
revision = '1da3ca7ba2cd'
down_revision = 'a2fa3e9ae30b'
branch_labels = None
depends_on = None

ELEMENT_TYPES = (
    ('default', 'Zadani elementi'),
    ('custom_functions', 'Posebne funkcije'),
    ('custom_variable_init', 'Inicijalizacija prilagođenih varijabli'),
    ('custom_variable_use', 'Korištenje prilagođenih varijabli'),
    ('custom_list', 'Prilagođene liste'),
    ('custom_tuple', 'Prilagođene n-torke'),
)

PROGRAMMING_ELEMENTS = (
    ('comment', 'Komentar', 'Postoji li komentar u kodu.', 'default'),
    ('function_def', 'Definicija funkcije', 'Je li učenik definirao vlastitu funkciju.', 'default'),
    ('loop', 'Petlja', 'Uporaba for ili while petlje.', 'default'),
    ('branching', 'Grananje', 'Uporaba if, elif ili else grananja.', 'default'),
    ('variable_init', 'Inicijalizacija varijable', 'Dodijeljena vrijednost varijabli.', 'default'),
    ('variable_use', 'Korištenje varijable', 'Čitanje ili promjena vrijednosti varijable.', 'default'),
    ('list', 'Lista', 'Stvaranje ili uporaba liste.', 'default'),
    ('tuple', 'N-torka', 'Inicijalizacija ili deklaracija n-torke.', 'default'),
    ('builtin_call', 'Ugrađeni poziv', 'Poziv ugrađene funkcije platforme.', 'default'),
    ('user_function_call', 'Korisnički poziv', 'Poziv funkcije koju je definirao učenik.', 'default'),
    ('detect_object_call', 'Prepoznavanje objekata', 'Poziv funkcije detect_object za prepoznavanje objekata.', 'custom_functions'),
    ('detect_object_conf_call', 'Provjera pouzdanosti prepoznavanja', 'Poziv funkcije detect_object_conf.', 'custom_functions'),
)



def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.create_foreign_key("user_groups_created_by_fkey", 'users', ['created_by'], ['id'])
        batch_op.create_foreign_key("user_groups_updated_by_fkey", 'users', ['updated_by'], ['id'])

    element_type_table = sa.table(
            'element_type',
            sa.column('id', sa.String),
            sa.column('user_readable_name', sa.String),
        )
    op.bulk_insert(element_type_table, [
            {'id': type_id, 'user_readable_name': name}
            for type_id, name in ELEMENT_TYPES
        ])
    
    programming_element_table = sa.table(
            'programming_element',
            sa.column('id', sa.String),
            sa.column('name', sa.String),
            sa.column('description', sa.Text),
            sa.column('created_at', sa.DateTime(timezone=True)),
            sa.column('updated_at', sa.DateTime(timezone=True)),
            sa.column('element_type_id', sa.String),
        )
    now = datetime.datetime.now(datetime.timezone.utc)
    op.bulk_insert(programming_element_table, [
            {
                'id': element_id,
                'name': name,
                'description': description,
                'created_at': now,
                'updated_at': now,
                'element_type_id': type_id,
            }
            for element_id, name, description, type_id in PROGRAMMING_ELEMENTS
        ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    programming_element_table = sa.table(
        'programming_element',
        sa.column('id', sa.String),
    )
    op.execute(
        programming_element_table.delete().where(
            programming_element_table.c.id.in_([
                element_id for element_id, _, _, _ in PROGRAMMING_ELEMENTS
            ])
        )
    )

    element_type_table = sa.table(
        'element_type',
        sa.column('id', sa.String),
    )
    op.execute(
        element_type_table.delete().where(
            element_type_table.c.id.in_([type_id for type_id, _ in ELEMENT_TYPES])
        )
    )

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        batch_op.drop_constraint("user_groups_created_by_fkey", type_='foreignkey')
        batch_op.drop_constraint("user_groups_updated_by_fkey", type_='foreignkey')

    # ### end Alembic commands ###
