"""added_groups_and_one_to_one_badge_task_link

Revision ID: a2fa3e9ae30b
Revises: 3f8c2a9b1e4d
Create Date: 2026-09-15 14:27:32.385234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2fa3e9ae30b'
down_revision = '3f8c2a9b1e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.add_column(sa.Column('relevant_activity_task_id', sa.Integer(), nullable=True))

    op.execute(sa.text("""
        UPDATE badges
        SET relevant_activity_task_id = CASE id
            WHEN 7 THEN 14
            WHEN 8 THEN 4
            WHEN 9 THEN 5
            WHEN 10 THEN 6
            WHEN 11 THEN 15
            WHEN 12 THEN 16
            WHEN 13 THEN 17
            WHEN 14 THEN 18
            WHEN 15 THEN 19
            WHEN 16 THEN 20
            WHEN 17 THEN 21
            WHEN 18 THEN 22
            WHEN 19 THEN 24
            WHEN 20 THEN 25
            WHEN 21 THEN 26
            WHEN 22 THEN 36
            WHEN 23 THEN 37
            WHEN 24 THEN 38
            WHEN 25 THEN 33
            WHEN 26 THEN 34
            WHEN 27 THEN 35
            WHEN 28 THEN 32
            WHEN 29 THEN 29
            WHEN 30 THEN 31
        END
        WHERE id BETWEEN 7 AND 30
    """))

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.alter_column(
            'relevant_activity_task_id',
            existing_type=sa.Integer(),
            nullable=False,
        )
        batch_op.create_unique_constraint('uq_badges_relevant_activity_task_id', ['relevant_activity_task_id'])
        batch_op.create_foreign_key(
            'fk_badges_relevant_activity_task_id_activity_tasks',
            'activity_tasks',
            ['relevant_activity_task_id'],
            ['id'],
        )

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_user_badges', ['user_id', 'badge_id'])

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        bind = op.get_bind()
        for fk in sa.inspect(bind).get_foreign_keys('user_groups'):
            if fk.get('name'):
                batch_op.drop_constraint(fk['name'], type_='foreignkey')

        batch_op.create_unique_constraint('uq_user_groups', ['user_id', 'group_id'])

        batch_op.create_foreign_key(
            'fk_user_groups_group_id_groups',
            'groups',
            ['group_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'fk_user_groups_user_id_users',
            'users',
            ['user_id'],
            ['id'],
        )

    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['started_by', 'activity_task_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_started_tasks', schema=None) as batch_op:
        batch_op.drop_constraint('user_started_tasks_started_by_activity_task_id_key', type_='unique')

    with op.batch_alter_table('user_groups', schema=None) as batch_op:
        bind = op.get_bind()
        for fk in sa.inspect(bind).get_foreign_keys('user_groups'):
            if fk.get('name'):
                batch_op.drop_constraint(fk['name'], type_='foreignkey')
        batch_op.drop_constraint('uq_user_groups', type_='unique')
        batch_op.create_foreign_key(
            'user_groups_group_id_fkey',
            'groups',
            ['group_id'],
            ['id'],
        )
        batch_op.create_foreign_key(
            'user_groups_user_id_fkey',
            'users',
            ['user_id'],
            ['id'],
        )

    with op.batch_alter_table('user_badges', schema=None) as batch_op:
        batch_op.drop_constraint('uq_user_badges', type_='unique')

    with op.batch_alter_table('badges', schema=None) as batch_op:
        batch_op.drop_constraint('fk_badges_relevant_activity_task_id_activity_tasks', type_='foreignkey')
        batch_op.drop_constraint('uq_badges_relevant_activity_task_id', type_='unique')
        batch_op.drop_column('relevant_activity_task_id')

    # ### end Alembic commands ###
