"""add_feedback_region_descriptions_to_programming_elements

Revision ID: d61e7f0a203f
Revises: 1da3ca7ba2cd
Create Date: 2026-10-07 10:12:41.862044

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd61e7f0a203f'
down_revision = '1da3ca7ba2cd'
branch_labels = None
depends_on = None

FEEDBACK_REGION_DESCRIPTIONS = {
    'comment': 'dio koda s opisnim bilješkama',
    'function_def': 'dio koda koji organizira vlastite radnje',
    'loop': 'dio koda koji ponavlja radnje',
    'branching': 'dio koda koji odlučuje između mogućih ponašanja',
    'variable_init': 'dio koda koji postavlja početne vrijednosti',
    'variable_use': 'dio koda koji koristi spremljene vrijednosti',
    'list': 'dio koda koji radi s više vrijednosti',
    'tuple': 'dio koda koji grupira više vrijednosti',
    'builtin_call': 'dio koda koji poziva naredbe okruženja',
    'user_function_call': 'dio koda koji poziva vlastite radnje',
    'detect_object_call': 'dio koda koji reagira na opažene objekte',
    'detect_object_conf_call': 'dio koda koji procjenjuje pouzdanost opažanja',
}




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programming_element', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feedback_region_description', sa.String(length=255), nullable=True))
        
    programming_element_table = sa.table(
        'programming_element',
        sa.column('id', sa.String(64)),
        sa.column('feedback_region_description', sa.String(255)),
    )
    for element_id, region_description in FEEDBACK_REGION_DESCRIPTIONS.items():
        op.execute(
            programming_element_table.update()
            .where(programming_element_table.c.id == element_id)
            .values(feedback_region_description=region_description)
        )

    op.execute(
        programming_element_table.update()
        .where(programming_element_table.c.feedback_region_description.is_(None))
        .values(feedback_region_description='opći strukturni dio koda')
    )

    with op.batch_alter_table('programming_element', schema=None) as batch_op:
        batch_op.alter_column(
            'feedback_region_description',
            existing_type=sa.String(length=255),
            nullable=False,
        )


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('programming_element', schema=None) as batch_op:
        batch_op.drop_column('feedback_region_description')

    # ### end Alembic commands ###
